{
    "contributors": [
        [
            "martinsarsini", 
            "lexrank"
        ], 
        [
            "baumgaro", 
            "email"
        ], 
        [
            "roignac", 
            "lexrank"
        ]
    ], 
    "title": "main menu\" editor, application properties not opening", 
    "comments": [
        {
            "date": "2011-10-31 22:46:38", 
            "sentences": [
                {
                    "is_in_lex_summary": true, 
                    "text": "The properties window for any application in the \"main menu\" editor does not open at all I am on 11.10 AMD64\n", 
                    "is_in_email_summary": true
                }
            ], 
            "name": "martinsarsini", 
            "email": "martinsarsini"
        }, 
        {
            "date": "2011-11-25 14:33:05", 
            "sentences": [
                {
                    "is_in_lex_summary": false, 
                    "text": "same for me - 11.10 AMD64\n", 
                    "is_in_email_summary": false
                }
            ], 
            "name": "baumgaro", 
            "email": "baumgaro"
        }, 
        {
            "date": "2011-11-25 14:33:19", 
            "sentences": [
                {
                    "is_in_lex_summary": false, 
                    "text": "Status changed to 'Confirmed' because the bug affects multiple users.\n", 
                    "is_in_email_summary": false
                }
            ], 
            "name": "janitor", 
            "email": "janitor"
        }, 
        {
            "date": "2011-11-29 09:41:47", 
            "sentences": [
                {
                    "is_in_lex_summary": true, 
                    "text": "This is bug is ridiculous, I am so surprised that nobody else had encountered the same issue. ", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "Perhaps this functionality is not much used, hence why Ubuntu's developers are not fixing this simple bug?\n", 
                    "is_in_email_summary": true
                }
            ], 
            "name": "martinsarsini", 
            "email": "martinsarsini"
        }, 
        {
            "date": "2011-11-29 09:54:55", 
            "sentences": [
                {
                    "is_in_lex_summary": true, 
                    "text": "opening alacarte from the terminal and clicking on any of the items property button I get the following error\n", 
                    "is_in_email_summary": true
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "Traceback (most recent call last):\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/share/alacarte/Alacarte/MainWindow.py\", line 382, in on_edit_properties_activate\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    process = subprocess.Popen(['gnome-desktop-item-edit', file_path], env=os.environ)\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/subprocess.py\", line 679, in __init__\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    errread, errwrite)\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/subprocess.py\", line 1239, in _execute_child\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    raise child_exception\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "OSError: [Errno 2] No such file or directory\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "\n", 
                    "is_in_email_summary": false
                }
            ], 
            "name": "martinsarsini", 
            "email": "martinsarsini"
        }, 
        {
            "date": "2011-11-29 09:58:26", 
            "sentences": [
                {
                    "is_in_lex_summary": false, 
                    "text": "ok, solved\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "the \"properties\" button uses gnome-desktop-item-edit, which is shipped with gnome-panel I had to run sudo apt-get install gnome-panel\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "the mystery is why Ubuntu didn't give any feedback whatsoever using that button, if a button silently fails... ", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "that's a bug\n", 
                    "is_in_email_summary": false
                }
            ], 
            "name": "martinsarsini", 
            "email": "martinsarsini"
        }, 
        {
            "date": "2011-11-29 10:36:04", 
            "sentences": [
                {
                    "is_in_lex_summary": false, 
                    "text": "This is duplicate of bug 826049\n", 
                    "is_in_email_summary": false
                }
            ], 
            "name": "roignac", 
            "email": "roignac"
        }
    ], 
    "id": "884498", 
    "project": "Launchpad", 
    "original_link": "https://bugs.launchpad.net/ubuntu/+bug/884498"
}